
export const MusicInstances = [
  {
    id: "t1",
    src: "/music/04. The Heaviest of Storms (Devotion, Pt. 1).mp3",
    title: "The Heaviest of Storms",
    artist: "Pale Honey",
    album: "Devotion",
    duration: "5:52",
    imageUrl: "/FieldOfView.jpg",
  },
  {
    id: "t2",
    src: "/music/GeoPoet - Rabbit Rebellion.mp3",
    title: "Rabbit Rebellion",
    artist: "GeoPoet",
    album: "Album Name",
    duration: "8:32",
    imageUrl: "/FieldOfView.jpg",
  },
  {
    id: "t3",
    src: "/music/Khruangbin - Maria También.mp3",
    title: "Maria Tambien",
    artist: "Khruangbin",
    album: "Album Name",
    duration: "3:10",
    imageUrl: "/FieldOfView.jpg",
  },
  {
    id: "t4",
    src: "/music/Roses.mp3",
    title: "Roses",
    artist: "Mareux",
    album: "Album Name",
    duration: "4:35",
    imageUrl: "/FieldOfView.jpg",
  },
  {
    id: "t5",
    src: "/music/Corbeau Hangs-Light to Dark.mp3",
    title: "Light to Dark",
    artist: "Corbeau Hangs",
    album: "Album Name",
    duration: "4:28",
    imageUrl: "/FieldOfView.jpg",
  },
  {
    id: "t6",
    src: "/music/1_4 - The Moment (Outro) - Bell Witch (128).mp3",
    title: "The Moment (Outro)",
    artist: "Bell Witch",
    album: "Album Name",
    duration: "3:06",
    imageUrl: "/FieldOfView.jpg",
  },
  {
    id: "t7",
    src: "/music/Sextile - contortion.mp3",
    title: "Contortion",
    artist: "Sextile",
    album: "Album Name",
    duration: "3:15",
    imageUrl: "/FieldOfView.jpg",
  },
  {
    id: "t8",
    src: "/music/Sufjan Stevens - To Be Alone With You.mp3",
    title: "To Be Alone With You",
    artist: "Sufjan Stevens",
    album: "Album Name",
    duration: "2:48",
    imageUrl: "/FieldOfView.jpg",
  },
  {
    id: "t9",
    src: "/music/01 Song Seven.mp3",
    title: "Song Seven",
    artist: "Interpol",
    album: "Album Name",
    duration: "4:52",
    imageUrl: "/FieldOfView.jpg",
  }, 
  
];
